# Generated by Django 4.0.5 on 2022-06-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SpecialistAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('start_reception', models.TimeField()),
                ('finish_reception', models.TimeField()),
                ('date', models.DateField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpecialistAPI.specialist')),
            ],
        ),
    ]
