# Generated by Django 4.0.5 on 2022-06-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('worker', models.CharField(max_length=50)),
                ('begining_worked_day', models.TimeField()),
                ('ending_worked_day', models.TimeField()),
                ('appointment', models.TimeField()),
            ],
        ),
    ]
