# Generated by Django 4.0.5 on 2022-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
