# Generated by Django 4.0.5 on 2022-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistAPI', '0002_alter_specialist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='appointment',
            field=models.IntegerField(),
        ),
    ]
