# Generated by Django 4.0.5 on 2022-06-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistAPI', '0003_alter_specialist_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='appointment',
            new_name='appointments',
        ),
    ]
