# Generated by Django 4.0.5 on 2022-06-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialistAPI', '0004_rename_appointment_specialist_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='appointments',
            new_name='diapason',
        ),
    ]
